name: CI/CD Pipeline with Provisioning

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the app
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create S3 bucket (if not exists)
      run: |
        aws s3 ls "s3://bluechip" || aws s3 mb "s3://bluechip"

    - name: Create Elastic Beanstalk application (if not exists)
      run: |
        aws elasticbeanstalk describe-applications --application-names my-app || aws elasticbeanstalk create-application --application-name my-app

    - name: Create Elastic Beanstalk environment (if not exists)
      run: |
        aws elasticbeanstalk describe-environments --application-name my-app --environment-names my-env || aws elasticbeanstalk create-environment --application-name my-app --environment-name my-env --solution-stack-name "64bit Amazon Linux 2 v3.1.1 running Node.js 14" --option-settings file://options.json

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        zip -r application.zip .
        aws s3 cp application.zip s3://bluechip/application.zip
        aws elasticbeanstalk create-application-version --application-name my-app --version-label v1 --source-bundle S3Bucket=my-bucket-name,S3Key=application.zip
        aws elasticbeanstalk update-environment --application-name my-app --environment-name my-env --version-label v1